name: Publish to GitHub Package Registry
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
          scope: aakashdeshpandesg
      #- name: Authenticate with GitHub Package Registry
       # run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_TOKEN }}" >> ~/.npmrc
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Publish package
        run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_TOKEN }}







          